version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1777:1777"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "1778:1778"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:1777
    restart: unless-stopped 